config/routes.rb
Rails.application.routes.draw do
  resources :places, only: [:index, :show, :new, :create, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  CATEGORIES = ['Playa', 'Parque']
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  reverse_geocoded_by :latitude, :longitude
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  after_validation :reverse_geocode
  belongs_to :user
  validates  :longitude, presence: true
  validates  :latitude, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :place
  belongs_to :user
  # validates :content, length: {minimum: 30}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :places
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @user = current_user
    @places = @user.places

  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :new, :update]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    p params[:places]
    @places = Place.geocoded
    @markers = @places.map do |place|
      if place.category == Place::CATEGORIES[0]
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { place: place }),
        image_url: helpers.asset_url('https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Beach-512.png'),
      }
      else
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { place: place }),
        image_url: helpers.asset_url('https://cdn0.iconfinder.com/data/icons/citycons/150/Citycons_park-512.png'),
      }
      end
    end
    

    if params[:places] == '' || params[:places] == nil
      @temp_place = Place.create(name:'Madrid', description: 'temp', address: 'Madrid')
      @center = [ @temp_place.latitude.dup, @temp_place.longitude.dup,]
      marker = {
        lat: @temp_place.latitude,
        lng: @temp_place.longitude,
        image_url: helpers.asset_url('compass.png'),
        infoWindow: render_to_string(partial: "info_window", locals: { place: @temp_place }),
      }
      @markers << marker
      @temp_place.delete
    
    else
      name = params[:places].split(',')
      p name
      @temp_place = Place.create(name:name[0], description: 'temp', address: params[:places])
      p params[:places]
      @center = [@temp_place.latitude.dup, @temp_place.longitude.dup]
      marker = {
        lat: @temp_place.latitude,
        lng: @temp_place.longitude,
        image_url: helpers.asset_url('compass.png'),
        infoWindow: render_to_string(partial: "info_window", locals: { place: @temp_place }),
      }
      @markers << marker
      @temp_place.delete
    end
  end

  def show
    set_place
    @review = Review.new
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to places_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @place.update(place_params)
    if @place.save
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  # def destroy
  #   @place.destroy
  #   redirect_to dashboard_path
  # end


  private

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :category, :description, :photo, :latitude, :longitude)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_user
  def new
    @review = Review.new
  end


  def edit
  end

  def create
    @place = Place.find(params[:place_id])
    @review = Review.new(review_params)
    @review.place = @place
    @review.user = @user
    if @review.save
      redirect_to place_path(@place, anchor: "review-#{@review.id}")
    else
      render 'places/show'
    end

  end

  private

  def set_user
    @user = current_user
  end

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169867332-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-169867332-1');
    </script>

    <title>Con mi Perrete - Playas y parques caninos para disfrutar con tu mejor amigo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.0.1/mapbox-gl.css' rel='stylesheet'>
    <%= favicon_link_tag asset_path('pugpugjs.svg') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>



    <%= render 'shared/flashes' %>
    <% if !current_page?(root_url)%>
    <%= render 'shared/navbar' %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/pages/_navbar_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-home">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dhkoueugk/image/upload/c_thumb,w_200,g_face/v1588940288/Perretes/pug_q3cza9.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link", id: "signup-home" %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to "Login", new_user_session_path, class: "nav-link", id: "login-home"%>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/dashboard.html.erb
dashboard.html.erb

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),url(https://images.unsplash.com/photo-1516727052521-08079c40df80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80); background-size: cover; background-position: center; ">
  <div class="container" style="height: 100vh">
    <div id="conmiperrete"></div>
    <p class="mt-2 mb-3" style="font-family: 'Lato', sans-serif; font-size: 21px; color: white; text-align: center">Encuentra playas y parques caninos en España para disfrutar con tu mejor amigo</p>
    <div class="container geocoder mb-5">
      <%= form_tag places_path, method: :get do%>
        <div id="homepageresponsive">

          <%= text_field_tag :places,
          params[:places], id: "place_address",
            placeholder: "Introduzca una localizacion",
            style: "border-radius: 24px; height: 44px;"%>

          <div class="botonbuscar">

            <%= submit_tag "Buscar", id: "searchbutton", class: "btn btn-primary ml-1",
            style: "border-radius: 24px; width: 110px; height: 44px; font-family: 'Lato';" %>
          </div>
        </div>

      <% end %>
    </div>

   <div class="d-flex justify-content-center">
    <%= link_to 'Ver todos los lugares', places_path, class:'btn-info mt-5 shadow-none', style:'border-radius: 5px; padding: 7px 12px' %>
  </div>
  </div>
</div>

app/views/places/_form.html.erb
<%= simple_form_for @place do |f| %>
<%= f.input :name, label: 'Nombre', label_html:{class:'font-weight-bold mt-2'}%>
<%= f.input :category, as: :radio_buttons,label: 'Categoría', label_class: 'font-weight-bold mt-2', collection: Place::CATEGORIES %>
<%= f.input :description, label: 'Descripción', label_html:{class:'font-weight-bold mt-2'} %>
<%= f.input :longitude, :as => :hidden %>
<%= f.input :latitude,  :as => :hidden  %>
<%= f.input :photo, as: :file, label:'Sube una foto', label_html:{class:'font-weight-bold mt-2'} %>
<div class='mt-4 pt-4'>
  <h3> Selecciona un lugar en el mapa </h3>
  <div id="mapper"
      class="container"
      style="width:auto; height: 600px; border: 5px"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    <<div id="menu">
      <input
      id="streets-v11" type="radio" name="rtoggle" value="streets" checked="checked"/>
      <label for="streets-v11">mapa</label>
      <input id="satellite-v9" type="radio" name="rtoggle" value="satellite" />
      <label for="satellite-v9">satelite</label>
      </div>
  </div>
</div>

<div class='d-flex justify-content-end'>
  <%= f.submit 'Crear', style:'border-radius:5px; padding:7px 12px', class:'btn-primary shadow-none mb-4'%>
  <% end %>
</div>


<pre id="coordinates" class="coordinates" style="visibility: hidden"></pre>

app/views/places/_info_window.html.erb
<div>

  <% if place.photo.attached?%>
    <%= cl_image_tag place.photo.key, width: 200, class: "card-img-top" %>
    <h4 class="mt-1" style="font-weight: bold;"><%= place.name %></h4>
    <p class="text-center"><%= place.address %></p>
    <div class="text-center"><%= link_to "Mas Info", place_path(place), class: "btn btn-primary text-center", style: "border-radius: 24px; width: 90px; font-family: 'Lato';" %></div>
  <% else %>
    <%= cl_image_tag("https://res.cloudinary.com/dhkoueugk/image/upload/v1592425348/Perretes/klara-kulikova-yWpEmVAT-cc-unsplash_usqyp4.jpg", width: 200, class: "card-img-top") %>
    <h4 class="mt-1" style="font-weight: bold;"><%= place.name %></h4>
    <p class="text-center"><%= place.address %></p>

  <% end %>

 </div>

app/views/places/edit.html.erb
<%= simple_form_for @place do |f| %>
<%= f.input :name, label: 'Nombre'%>
<%= f.input :category, as: :radio_buttons, collection: Place::CATEGORIES, label: 'Categoría' %>
<%= f.input :description, label: 'Descripción' %>
<%= f.input :longitude, :as => :hidden %>
<%= f.input :latitude,  :as => :hidden  %>
<%= f.input :photo, as: :file, label_:'Sube una foto' %>
<%= f.submit 'Crear'%>
<% end %>

<div id="mapper"
      class="container"
     style="width: 80%; height: 600px; border: 5px"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<button id='remover'>Add satellite</button>


<pre id="coordinates" class="coordinates"></pre>

app/views/places/index.html.erb
<div  id="map"
       id="geocoder"
       style="position: absolute;
        width: 100%;
        height: 93%;
        margin-left: auto;
        margin-right: auto;
        left: 0;
        right: 0;
        z-index: 0;"
       data-markers="<%= @markers.to_json %>"
       data-center="<%= @center.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
<div class="row"
      style="justify-content: space-between;
      position: relative;

      left: 0;
      right: 0;
      z-index: 2;" >
  <div class=" col-md-6 ml-1 mr-1 geocoder mt-1" id="searchform" >
    <%= form_tag places_path, method: :get do %>
      <div class="d-flex mb-2 mt-2" >
        <%= text_field_tag :places,
        params[:places], id: "place_address",
          placeholder: "Introduzca una localizacion",
          style: "border-radius: 24px; height: 44px; font-family: 'lato'; font-size: 14px; " %>
          <div>
      <%= submit_tag "Buscar", id: "searchbutton", class: "ml-1 btn btn-primary",
        style: "border-radius: 24px; width: 110px; height: 44px; font-family: 'lato';" %>
      </div>
      </div>

    <% end %>
    </div>

</div>

  <div class="col-md-2 "
        style="justify-content: flex-end;
              bottom: 0;
              position: absolute;
              z-index: 1;
              padding-left: 5px;
              margin-bottom: 5px;
              max-width: 65px;">
      <div class="text-left"
            style="background: #ffffffb3;
                  border-radius: 25px;
                  padding: 15px 2px 1px 0;
                  margin-bottom: 11px;
                  width: 44px;">
        <div>
        <img class="text-center" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Beach-512.png" style="width: 25px; height: 25px; margin-left: 8px; ">
        <p class="mr-1 ml-1 text-center" style="font-family: 'lato';"> Playa</p>
        </div>
        <div>
        <img class="text-center" src="https://cdn0.iconfinder.com/data/icons/citycons/150/Citycons_park-512.png" style="width: 25px; height: 25px; margin-left: 8px;">
        <p class="ml-1 mr-1 text-center" style="font-family: 'lato';">Parque</p>
        </div>
      </div>
     <button class="btn btn-info" style="margin-bottom: 5px; border-radius: 24px; width: 110px; height: 44px; font-family: 'Lato'; box-shadow: 10px 10px 20px -13px rgba(0,0,0,0.47);"><%= link_to "Crear Lugar", new_place_path, style: "text-decoration: none; color: white" %></button>

    </div>


    <div id="menu">
    <input
    id="streets-v11" type="radio" name="rtoggle" value="streets" checked="checked"/>
    <label for="streets-v11">mapa</label>
    <input id="satellite-v9" type="radio" name="rtoggle" value="satellite" />
    <label for="satellite-v9">satelite</label>
    </div>



</div>

app/views/places/new.html.erb
<div class="container mt-5 pb-5 px-5 px-sm-0 mb-5" >
  <h2>Añade un lugar</h2>
  <%= render 'form' %>
  <div class="d-flex justify-content-center">
    <%= link_to 'Ver todos los lugares', places_path, class:'btn-info', style:'border-radius: 5px; padding: 7px 12px' %>
  </div>
</div>

app/views/places/show.html.erb
<div class="container container mt-5 pb-5 px-5 px-sm-0 mb-5">
  <div class="row">
    <% if @place.photo.attached?%>
      <div class="col-lg">
         <%= cl_image_tag @place.photo.key, width: 600, height: 400, crop: :fill, class: "img-fluid" %>
      </div>
      <% else %>
      <div class="col-lg">
          <%= cl_image_tag("https://res.cloudinary.com/dhkoueugk/image/upload/v1592425348/Perretes/klara-kulikova-yWpEmVAT-cc-unsplash_usqyp4.jpg", width: 600, height: 400, crop: :fill, class: "card-img-top") %>
      </div>
      <% end %>
    <div class="col-md">
      <div class="mb-5 pt-3">
        <h1 style="font-weight: bold;"><%= @place.name %></h1>
        <div class="mt-3">
          <p><%= @place.description %></p>
        </div>
        
      </div>
      <div class="mt-3 mb-5">
        <h3>Servicios disponibles:</h3>
        <div class="mt-5">
          <ul class="pl-4 pr-4">
            <li><i class="fas fa-shower fa-lg"></i></li>
            <li><i class="fas fa-restroom fa-lg"></i></li>
            <li><i class="fas fa-beer fa-lg"></i></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="reviews">
   <%= render 'reviews/form' %>
  </div>
   <div class="d-flex justify-content-center">
    <%= link_to 'Ver todos los lugares', places_path, class:'btn-info shadow-none', style:'border-radius: 5px; padding: 7px 12px' %>
  </div>


</div>

app/views/reviews/_form.html.erb
<div class="mt-2 mt-md-5">
  <% if @place.reviews.blank? %>
    <h3>Sé el primero en dejar un comentario!</h3>
  <% else %>
    <h3>Comentarios</h3>
    <% @place.reviews.each do |review| %>
      <% if review.user == nil %>
        <p id="review-<%= review.id %>"><%= review.content %></p>
      <% else %>
        <b><%= review.user.username %></b>
        <p id="review-<%= review.id %>"><%= review.content %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="mt-3">
  <div class="mb-4">
    <h4>Tu valoración</h4>
  </div>
  <div>
    <%= simple_form_for([ @place, @review ], remote: true) do |f| %>
      <%= f.input :content,label:false, as: :text %>
      <div class="d-flex justify-content-end mt-4 mb-5">
        <%= f.submit 'Crea una review', type:'button', class:'btn-primary shadow-none outline-none', style:'border-radius:5px' %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="box-shadow: 10px 10px 20px -13px rgba(0,0,0,0.47); z-index: 1; height: 8%">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Con_mi_Perrete1_werbla.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item grow">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/navbar' %>
<div class="container" style="padding-top: 90px;">
  <h1>Edita tu perfil:</h1>
    <div class=“pt-10”>
     <%= simple_form_for @user do |f| %>
       <%= f.input :name %>
       <%= f.input :bio %>
       <%= f.input :email %>

       <%= f.submit("Guardar", class: "btn btn-secondary") %>
     <% end %>

     <p><%= link_to "Volver", dashboard_path, class: 'btn mt-5' %></p>
  </div>
</div>